[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino

monitor_speed = 115200
upload_speed = 1500000

extra_scripts =
    pre:scripts/fetch_mbelib_classic.py
    pre:scripts/link_tx_ambe_rust.py

lib_deps =
    m5stack/M5Cardputer
    m5stack/M5Unified

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -O3
    -ffast-math
    -fno-math-errno

; Firmware branding
custom_fw_name = IU2VTP_Cardputer_DMR_Terminal
